title: "Exposed Host"
description: < Memory regions from day to day experiences
  twitter: <a href="https://twitter.com/cs0sf">@cs0sf</a>
baserl: ""
url: ""
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
