title: "Exposed Host"
description: > 
  Memory leaks from day to day experiences<br>
  twitter: <a href="https://twitter.com/cs0sf">@cs0sf</a>
baserl: ""
url: ""
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
